import { createContext, useContext, useState, useEffect } from 'react';

// //  TRANSLATIONS — Add or edit translations here
// Languages: en = English | ar = Arabic | ku = Kurdish (Sorani)
const T = {
  en: {
    home:'Home', dashboard:'Dashboard', tenants:'Tenants', payments:'Payments', receipts:'Receipts', receiveReceipts:'Receive Receipts', giveReceipts:'Give Receipts',
    expenses:'Expenses', reports:'Reports', whatsapp:'WhatsApp',
    settings:'Settings', users:'Users', main:'Main', contractSection:'Contracts', adminSection:'Admin',
    save:'Save', cancel:'Cancel', edit:'Edit', delete:'Delete', add:'Add',
    search:'Search...', close:'Close', loading:'Loading...', actions:'Actions',
    yes:'Yes', no:'No', later:'Later', saveChanges:'Save Changes', noResults:'No results found.', refresh:'Refresh', status:'Status',
    confirmDelete:'This cannot be undone.', all:'All',
    expandAll:'Expand All', collapseAll:'Collapse All',
    username:'Username', password:'Password', signIn:'Sign In ',
    wrongCredentials:'Invalid username or password.', logout:'Sign Out',
    welcomeBack:'Welcome back', signInSub:'Sign in to your RentPro account',
    loginFeature1:'Payment tracking', loginFeature2:'WhatsApp reminders',
    loginFeature3:'Financial reports', loginFeature4:'Team management',
    loginTagline:'Manage your properties with confidence',
    loginDesc:'Track tenants, payments, expenses and stay connected via WhatsApp — all in one place.',
    dashTitle:'Dashboard', dashSub:'Overview of your rental portfolio',
    sellContract:'Sell Contract', rentContract:'Rent Contract',
    receiptShortcut:'Receipt', ankets:'Ankets',
    contractShortcut:'Contracts', receiptShortcutMeta:'Receipts',
    anketsMeta:'Forms and records', portfolioOverview:'Portfolio overview',
    tenantPaymentReceipts:'Tenant payment receipts', ownerPayoutReceipts:'Owner payout receipts',
    savedRecords:'saved', ownerReceipts:'owner receipts',
    monthlyIncome:'Monthly Income', collected:'Collected', outstanding:'Outstanding',
    netIncome:'Net Income', activeTenants:'active tenants', paidPayments:'paid payments', paymentRecords:'records',
    pendingLabel:'pending', lateLabel:'late', afterExpenses:'After expenses', activeStatus:'Active',
    dueSoon:'Due in 5 Days', latePayments:'Late Payments',
    noDueSoon:'No payments due in the next 5 days', noLate:'No late payments — all good!',
    allTenants:'All Tenants', manage:'Manage ',
    tenant:'Tenant', apartment:'Apartment', type:'Type', rent:'Rent',
    payDay:'Pay Day', contract:'Contract', progress:'Progress',
    tenantsTitle:'Tenants', manageTenants:'Manage all tenants',
    addTenant:'+ Add Tenant', addNewTenant:'Add New Tenant',
    editTenant:'Edit Tenant', noTenants:'No tenants yet.',
    fullName:'Full Name *', phone:'Phone (with country code)',
    aptUnit:'Apartment / Unit *', location:'Location / City',
    ownerName:'Owner Name', ownerPhone:'Owner Phone',
    monthlyRent:'Monthly Rent', payDayNum:'Pay Day (1–31)',
    propertyType:'Property Type', residential:'Residential',
    villa:'Villa', commercial:'Commercial', office:'Office',
    contractStart:'Contract Start', contractEnd:'Contract End',
    notes:'Notes (optional)', exportCSV:'Export CSV',
    owner:'Owner', paid:'Paid', totalTenants:'Total',
    allPaidLabel:'All Paid', phoneTip:'Iraq: 9647701234567 | UAE: 971501234567',
    cancelAdd:'Cancel', hideForm:'Hide Form', showForm:'Add Tenant',
    paymentsTitle:'Payments', paymentsSub:'Click a row to toggle Pending Paid',
    addMonth:'+ Add Month', markPaid:'Mark Paid', markPending:'Pending',
    printReceipt:'Print Receipt', noPaymentRecords:'No payment records. Click + Add Month.',
    paidStatus:'Paid', pendingStatus:'Pending', lateStatus:'Late',
    month:'Month', paidDate:'Date Paid', amount:'Amount',
    searchTenants:'Search tenants...', totalPaid:'Total Paid',
    totalPending:'Total Pending', totalLate:'Total Late',
    expensesTitle:'Expenses', expensesSub:'Track maintenance and property expenses',
    addExpense:'+ Add Expense', editExpense:'Edit Expense', noExpenses:'No expenses yet.',
    description:'Description', descriptionKey:'Description', category:'Category', property:'Property',
    date:'Date', total:'Total', totalExpenses:'Total Expenses',
    maintenance:'Maintenance', utilities:'Utilities', repairs:'Repairs',
    cleaning:'Cleaning', management:'Management', other:'Other',
    expenseRecords:'records',
    reportsTitle:'Reports', reportsSub:'Financial overview of your portfolio',
    totalCollected:'Total Collected', totalExp:'Total Expenses',
    revenueByTenant:'Revenue by Tenant', expByCategory:'Expenses by Category',
    downloadCSV:'Download CSV', print:'Print',
    noExpensesYet:'No expenses recorded yet.',
    waTitle:'WhatsApp', waSub:'Auto-reminders at 9:00 AM daily',
    connectionStatus:'Connection Status', sendAll:'Send All Reminders',
    sendReminder:'Remind', activityLogs:'Activity Logs', clearLogs:'Clear',
    connected:'Connected', scanQRCode:'Scan QR Code', starting:'Starting...',
    waReadyShort:'ON', waQrShort:'QR',
    disconnected:'Disconnected', serverOffline:'Server Offline',
    scanInstruction:'Open WhatsApp Menu Linked Devices Link a Device',
    autoReconnecting:'Auto-reconnecting...', hasPending:'Has pending', allPaidWA:'All paid',
    noTenantsWA:'No tenants', sendAllBtn:'Send All Reminders',
    settingsTitle:'Settings', settingsSub:'Configure RentPro for your business',
    businessSettings:'Business Settings', appName:'App Name',
    companyName:'Company Name', appLogo:'Company Logo', chooseLogo:'Choose Logo', removeLogo:'Remove Logo',
    contractCoordinator:'Contract Coordinator', currency:'Currency', timezone:'Timezone',
    reminderHour:'Auto-Reminder Hour (0–23)', saveSettings:'Save Settings',
    security:'Security', currentPassword:'Current Password',
    newUsername:'New Username (optional)', newPassword:'New Password (optional)',
    updateCredentials:'Update Credentials', keepCurrent:'Leave blank to keep current',
    messageTemplates:'WhatsApp Message Templates',
    reminderMsg:'Reminder Message', lateMsg:'Late Payment Alert',
    saveTemplates:'Save Templates', availableVars:'Available variables',
    usersTitle:'Users', usersSub:'Manage agent and admin accounts',
    addUser:'+ Add User', editUser:'Edit User', noUsers:'No users yet.',
    createdBy:'Created By', createdAgents:'Agents Created', passwordHidden:'Hidden - reset only',
    role:'Role', agent:'Agent', adminRole:'Admin', ownerRole:'Owner/Admin', developerRole:'Developer', email:'Email',
    createUser:'Create User', deleteUser:'Delete User',
    agentReports:'Agent Reports', agentReportsSub:'Review owner and agent activity',
    totalActivity:'Total Activity', lastActivity:'Last Activity',
    youLabel:'You', nameLabel:'Full Name',
    receiptTitle:'Payment Receipt', receiptNo:'Receipt No.',
    receiptDate:'Date', receiptTenant:'Tenant', receiptProperty:'Property',
    receiptPeriod:'Period', receiptAmount:'Amount Paid', receiptStatus:'Status',
    receiptNote:'This is an official payment receipt.',
    darkMode:'Dark Mode', lightMode:'Light Mode',
    language:'Language',
    renewalMsg:'Rent Contract Renewal Message',
    renewRentContract:'Renew Rent Contract',
    renewRentContractsTitle:'Renew Rent Contracts',
    renewRentContractsSub:'Track rent contracts that are near renewal and send WhatsApp reminders.',
    sendRenewalReminder:'Send Renewal Reminder',
    sendAllRenewals:'Send All Due',
    renewalDueSoon:'Due Soon',
    expired:'Expired',
    daysLeft:'Days Left',
    noRenewals:'No rent contracts near renewal.',
    renewalWindow:'Renewal Window',
    notifications:'Notifications',
    notificationsSub:'Send alerts to the team and track what has been read.',
    sendNotification:'Send Notification',
    notificationTitle:'Title',
    notificationMessage:'Message',
    scheduledAt:'Send Time',
    sendByWhatsapp:'Send by WhatsApp',
    sendToAllAgents:'Send to all agents',
    selectAgents:'Select agents',
    unread:'Unread',
    read:'Read',
    markAsRead:'Mark as read',
    noNotifications:'No notifications yet.',
    sentNotifications:'Sent Notifications',
    profit:'Profit',
    profitTitle:'Profit',
    profitSub:'Review contract profit, expenses, and net result.',
    recordProfit:'Record Profit',
    profitAmount:'Profit Amount',
    profitCurrency:'Profit Currency',
    saveProfitAndPrint:'Save Profit & Print',
    printWithoutProfit:'Print without profit',
    profitPromptTitle:'Contract Profit',
    profitPromptSub:'Before printing, record the profit received from this contract.',
    fromDate:'From',
    toDate:'To',
    exportExcel:'Export Excel',
    grossProfit:'Gross Profit',
    netProfit:'Net Profit',
    noProfits:'No profit records yet.',
  },

  ar: {
    home:'الرئيسية', dashboard:'لوحة التحكم', tenants:'المستأجرون', payments:'المدفوعات', receipts:'الإيصالات', receiveReceipts:'إيصالات القبض', giveReceipts:'إيصالات الدفع',
    expenses:'المصروفات', reports:'التقارير', whatsapp:'واتساب',
    settings:'الإعدادات', users:'المستخدمون', main:'الرئيسية', contractSection:'العقود', adminSection:'الإدارة',
    save:'حفظ', cancel:'إلغاء', edit:'تعديل', delete:'حذف', add:'إضافة',
    search:'بحث...', close:'إغلاق', loading:'جاري التحميل...', actions:'الإجراءات',
    yes:'نعم', no:'لا', later:'لاحقاً', saveChanges:'حفظ التغييرات', noResults:'لا توجد نتائج.', refresh:'تحديث', status:'الحالة',
    confirmDelete:'لا يمكن التراجع عن هذا الإجراء.', all:'الكل',
    expandAll:'توسيع الكل', collapseAll:'طي الكل',
    username:'اسم المستخدم', password:'كلمة المرور', signIn:'تسجيل الدخول ',
    wrongCredentials:'اسم مستخدم أو كلمة مرور غير صحيحة.', logout:'تسجيل الخروج',
    welcomeBack:'مرحباً بعودتك', signInSub:'سجّل دخولك إلى حساب RentPro',
    loginFeature1:'تتبع المدفوعات', loginFeature2:'تذكيرات واتساب',
    loginFeature3:'تقارير مالية', loginFeature4:'إدارة الفريق',
    loginTagline:'إدارة عقاراتك بثقة',
    loginDesc:'تتبع المستأجرين والمدفوعات والمصروفات وابقَ على تواصل عبر واتساب — كل شيء في مكان واحد.',
    dashTitle:'لوحة التحكم', dashSub:'نظرة عامة على محفظتك العقارية',
    sellContract:'عقد بيع', rentContract:'عقد إيجار',
    receiptShortcut:'إيصال', ankets:'استبيانات',
    contractShortcut:'العقود', receiptShortcutMeta:'الإيصالات',
    anketsMeta:'النماذج والسجلات', portfolioOverview:'نظرة عامة على المحفظة',
    tenantPaymentReceipts:'إيصالات دفع المستأجرين', ownerPayoutReceipts:'إيصالات دفع المالكين',
    savedRecords:'محفوظ', ownerReceipts:'إيصالات المالكين',
    monthlyIncome:'الدخل الشهري', collected:'المحصّل', outstanding:'المتبقي',
    netIncome:'صافي الدخل', activeTenants:'مستأجر نشط', paidPayments:'مدفوعة', paymentRecords:'سجلات',
    pendingLabel:'معلقة', lateLabel:'متأخرة', afterExpenses:'بعد المصروفات', activeStatus:'نشط',
    dueSoon:'مستحق خلال 5 أيام', latePayments:'مدفوعات متأخرة',
    noDueSoon:'لا مدفوعات مستحقة خلال 5 أيام', noLate:'لا توجد مدفوعات متأخرة — ممتاز!',
    allTenants:'جميع المستأجرين', manage:'إدارة ',
    tenant:'المستأجر', apartment:'الشقة', type:'النوع', rent:'الإيجار',
    payDay:'يوم الدفع', contract:'العقد', progress:'التقدم',
    tenantsTitle:'المستأجرون', manageTenants:'إدارة جميع المستأجرين',
    addTenant:'+ إضافة مستأجر', addNewTenant:'إضافة مستأجر جديد',
    editTenant:'تعديل المستأجر', noTenants:'لا يوجد مستأجرون بعد.',
    fullName:'الاسم الكامل *', phone:'الهاتف (مع رمز البلد)',
    aptUnit:'الشقة / الوحدة *', location:'الموقع / المدينة',
    ownerName:'اسم المالك', ownerPhone:'هاتف المالك',
    monthlyRent:'الإيجار الشهري', payDayNum:'يوم الدفع (1–31)',
    propertyType:'نوع العقار', residential:'سكني',
    villa:'فيلا', commercial:'تجاري', office:'مكتب',
    contractStart:'بداية العقد', contractEnd:'نهاية العقد',
    notes:'ملاحظات (اختياري)', exportCSV:'تصدير CSV',
    owner:'المالك', paid:'مدفوع', totalTenants:'الإجمالي',
    allPaidLabel:'الكل مدفوع', phoneTip:'العراق: 9647701234567 | الإمارات: 971501234567',
    cancelAdd:'إلغاء', hideForm:'إخفاء النموذج', showForm:'إضافة مستأجر',
    paymentsTitle:'المدفوعات', paymentsSub:'انقر على الصف لتبديل الحالة: معلق مدفوع',
    addMonth:'+ إضافة شهر', markPaid:'تحديد كمدفوع', markPending:'معلق',
    printReceipt:'طباعة الإيصال', noPaymentRecords:'لا سجلات. انقر + إضافة شهر.',
    paidStatus:'مدفوع', pendingStatus:'معلق', lateStatus:'متأخر',
    month:'الشهر', paidDate:'تاريخ الدفع', amount:'المبلغ',
    searchTenants:'البحث عن مستأجر...', totalPaid:'إجمالي المدفوع',
    totalPending:'إجمالي المعلق', totalLate:'إجمالي المتأخر',
    expensesTitle:'المصروفات', expensesSub:'تتبع مصروفات الصيانة والعقارات',
    addExpense:'+ إضافة مصروف', editExpense:'تعديل مصروف', noExpenses:'لا مصروفات بعد.',
    description:'الوصف', category:'الفئة', property:'العقار',
    date:'التاريخ', total:'المجموع', totalExpenses:'إجمالي المصروفات',
    maintenance:'صيانة', utilities:'مرافق', repairs:'إصلاحات',
    cleaning:'تنظيف', management:'إدارة', other:'أخرى',
    expenseRecords:'سجل',
    reportsTitle:'التقارير', reportsSub:'نظرة مالية شاملة على محفظتك',
    totalCollected:'إجمالي المحصّل', totalExp:'إجمالي المصروفات',
    revenueByTenant:'الإيرادات حسب المستأجر', expByCategory:'المصروفات حسب الفئة',
    downloadCSV:'تحميل CSV', print:'طباعة',
    noExpensesYet:'لا توجد مصروفات مسجّلة بعد.',
    waTitle:'واتساب', waSub:'تذكيرات تلقائية يومياً الساعة 9 صباحاً',
    connectionStatus:'حالة الاتصال', sendAll:'إرسال لجميع',
    sendReminder:'تذكير', activityLogs:'سجل النشاط', clearLogs:'مسح',
    connected:'متصل', scanQRCode:'امسح رمز QR', starting:'جاري التشغيل...',
    waReadyShort:'متصل', waQrShort:'QR',
    disconnected:'انقطع الاتصال', serverOffline:'الخادم غير متصل',
    scanInstruction:'افتح واتساب القائمة الأجهزة المرتبطة ربط جهاز',
    autoReconnecting:'إعادة الاتصال تلقائياً...', hasPending:'لديه مدفوعات معلقة', allPaidWA:'الكل مدفوع',
    noTenantsWA:'لا يوجد مستأجرون', sendAllBtn:'إرسال لجميع',
    settingsTitle:'الإعدادات', settingsSub:'إعداد RentPro لعملك',
    businessSettings:'إعدادات الأعمال', appName:'اسم التطبيق',
    companyName:'اسم الشركة', appLogo:'شعار الشركة', chooseLogo:'اختيار الشعار', removeLogo:'حذف الشعار',
    contractCoordinator:'منسق العقد', currency:'العملة', timezone:'المنطقة الزمنية',
    reminderHour:'ساعة التذكير التلقائي (0–23)', saveSettings:'حفظ الإعدادات',
    security:'الأمان', currentPassword:'كلمة المرور الحالية',
    newUsername:'اسم مستخدم جديد (اختياري)', newPassword:'كلمة مرور جديدة (اختياري)',
    updateCredentials:'تحديث بيانات الدخول', keepCurrent:'اتركه فارغاً للإبقاء على الحالي',
    messageTemplates:'قوالب رسائل واتساب',
    reminderMsg:'رسالة التذكير', lateMsg:'تنبيه الدفع المتأخر',
    saveTemplates:'حفظ القوالب', availableVars:'المتغيرات المتاحة',
    usersTitle:'المستخدمون', usersSub:'إدارة حسابات الوكلاء',
    addUser:'+ إضافة مستخدم', editUser:'تعديل مستخدم', noUsers:'لا يوجد مستخدمون بعد.',
    createdBy:'تم إنشاؤه بواسطة', createdAgents:'الوكلاء المنشؤون', passwordHidden:'مخفي - إعادة تعيين فقط',
    role:'الدور', agent:'وكيل', adminRole:'مدير', ownerRole:'المالك / المدير', developerRole:'المطور', email:'البريد الإلكتروني',
    createUser:'إنشاء مستخدم', deleteUser:'حذف المستخدم',
    agentReports:'تقارير الوكلاء', agentReportsSub:'مراجعة نشاط المالك والوكلاء',
    totalActivity:'إجمالي النشاط', lastActivity:'آخر نشاط',
    youLabel:'أنت', nameLabel:'الاسم الكامل',
    receiptTitle:'إيصال دفع', receiptNo:'رقم الإيصال',
    receiptDate:'التاريخ', receiptTenant:'المستأجر', receiptProperty:'العقار',
    receiptPeriod:'الفترة', receiptAmount:'المبلغ المدفوع', receiptStatus:'الحالة',
    receiptNote:'هذا إيصال دفع رسمي.',
    darkMode:'الوضع الداكن', lightMode:'الوضع الفاتح',
    language:'اللغة',
    renewalMsg:'رسالة تجديد عقد الإيجار',
    renewRentContract:'تجديد عقد الإيجار',
    renewRentContractsTitle:'تجديد عقود الإيجار',
    renewRentContractsSub:'متابعة عقود الإيجار القريبة من التجديد وإرسال تذكيرات واتساب.',
    sendRenewalReminder:'إرسال تذكير التجديد',
    sendAllRenewals:'إرسال للجميع',
    renewalDueSoon:'قريب التجديد',
    expired:'منتهي',
    daysLeft:'الأيام المتبقية',
    noRenewals:'لا توجد عقود إيجار قريبة من التجديد.',
    renewalWindow:'مدة التذكير',
    notifications:'الإشعارات',
    notificationsSub:'إرسال تنبيهات للفريق ومتابعة المقروء.',
    sendNotification:'إرسال إشعار',
    notificationTitle:'العنوان',
    notificationMessage:'الرسالة',
    scheduledAt:'وقت الإرسال',
    sendByWhatsapp:'إرسال عبر واتساب',
    sendToAllAgents:'إرسال لكل الوكلاء',
    selectAgents:'اختيار الوكلاء',
    unread:'غير مقروء',
    read:'مقروء',
    markAsRead:'تحديد كمقروء',
    noNotifications:'لا توجد إشعارات بعد.',
    sentNotifications:'الإشعارات المرسلة',
    profit:'الأرباح',
    profitTitle:'الأرباح',
    profitSub:'مراجعة أرباح العقود والمصروفات والصافي.',
    recordProfit:'تسجيل الربح',
    profitAmount:'مبلغ الربح',
    profitCurrency:'عملة الربح',
    saveProfitAndPrint:'حفظ الربح والطباعة',
    printWithoutProfit:'طباعة بدون ربح',
    profitPromptTitle:'ربح العقد',
    profitPromptSub:'قبل الطباعة، سجل الربح المستلم من هذا العقد.',
    fromDate:'من',
    toDate:'إلى',
    exportExcel:'تصدير Excel',
    grossProfit:'إجمالي الربح',
    netProfit:'صافي الربح',
    noProfits:'لا توجد أرباح مسجلة بعد.',
  },

  ku: {
    home:'ماڵەوە', dashboard:'داشبۆرد', tenants:'بنکەنشینان', payments:'پارەدانەکان', receipts:'پسوولەکان', receiveReceipts:'پسوولەی پارە وەرگرتن', giveReceipts:'پسوولەکانی پارەدان',
    expenses:'خەرجەکان', reports:'ڕاپۆرتەکان', whatsapp:'واتساپ',
    settings:'ڕێکخستنەکان', users:'بەکارهێنەران', main:'سەرەکی', contractSection:'گرێبەستەکان', adminSection:'بەڕێوەبردن',
    save:'پاشەکەوت', cancel:'پاشگەزبوونەوە', edit:'دەستکاری', delete:'سڕینەوە', add:'زیادکردن',
    search:'گەڕان...', close:'داخستن', loading:'چاوەڕوان بە...', actions:'کردارەکان',
    yes:'بەڵێ', no:'نەخێر', later:'دواتر', saveChanges:'پاشەکەوتکردنی گۆڕانکاری', noResults:'ئەنجامی نەدۆزرایەوە.', refresh:'نوێکردنەوە', status:'دۆخ',
    confirmDelete:'ئەم کردارە ناگەڕێتەوە.', all:'هەموو',
    expandAll:'فراوانکردنی هەموو', collapseAll:'داخستنی هەموو',
    username:'ناوی بەکارهێنەر', password:'وشەی نهێنی', signIn:'چوونەژوورەوە ',
    wrongCredentials:'ناوی بەکارهێنەر یان وشەی نهێنی هەڵەیە.', logout:'دەرچوون',
    welcomeBack:'بەخێربێیتەوە', signInSub:'بچۆ ژوورەوە بۆ ئەکاونتی RentPro',
    loginFeature1:'شوێنکەوتنەوەی پارەدان', loginFeature2:'بیرخستنەوەی واتساپ',
    loginFeature3:'ڕاپۆرتی دارایی', loginFeature4:'بەڕێوەبردنی تیم',
    loginTagline:'ملکەکانت بە ئارامی بەڕێوەبە',
    loginDesc:'شوێنکەوتنەوەی بنکەنشینان، پارەدانەکان، خەرجەکان و مانەوە بەستراوەوە لە ڕێگای واتساپ — هەموو شتێک لە شوێنێکدا.',
    dashTitle:'داشبۆرد', dashSub:'پوختەی بەڕێوەبردنی کرێکاران',
    sellContract:'گرێبەستی فرۆشتن', rentContract:'گرێبەستی کرێ',
    receiptShortcut:'پسووڵە', ankets:'ئانکێتەکان',
    contractShortcut:'گرێبەستەکان', receiptShortcutMeta:'پسووڵەکان',
    anketsMeta:'فۆڕم و تۆمارەکان', portfolioOverview:'پوختەی کۆگای موڵک',
    tenantPaymentReceipts:'پسووڵەی پارەدانی کرێچی', ownerPayoutReceipts:'پسووڵەی پارەدانی خاوەن',
    savedRecords:'پاشەکەوتکراو', ownerReceipts:'پسووڵەی خاوەن',
    monthlyIncome:'داهاتی مانگانە', collected:'کۆکراوە', outstanding:'ماوەی چاوەڕوان',
    netIncome:'داهاتی خاڵص', activeTenants:'بنکەنشینی چالاک', paidPayments:'پارەدراو', paymentRecords:'تۆمار',
    pendingLabel:'چاوەڕوان', lateLabel:'دواکەوتوو', afterExpenses:'دوای خەرج', activeStatus:'چالاک',
    dueSoon:'لە 5 ڕۆژی داهاتوودا', latePayments:'پارەدانی دواکەوتوو',
    noDueSoon:'هیچ پارەدانێک لە 5 ڕۆژ نییە', noLate:'پارەدانی دواکەوتوو نییە — باشە!',
    allTenants:'هەموو بنکەنشینان', manage:'بەڕێوەبردن ',
    tenant:'بنکەنشین', apartment:'شووقە', type:'جۆر', rent:'کرێ',
    payDay:'ڕۆژی پارەدان', contract:'گرێبەست', progress:'پێشکەوتن',
    tenantsTitle:'بنکەنشینان', manageTenants:'بەڕێوەبردنی هەموو بنکەنشینان',
    addTenant:'+ زیادکردنی بنکەنشین', addNewTenant:'زیادکردنی بنکەنشینی نوێ',
    editTenant:'دەستکاریکردنی بنکەنشین', noTenants:'بنکەنشین نییە هێشتا.',
    fullName:'ناوی تەواو *', phone:'تەلەفۆن (بە کۆدی وڵات)',
    aptUnit:'شووقە / یەکە *', location:'شوێن / شار',
    ownerName:'ناوی خاوەن', ownerPhone:'تەلەفۆنی خاوەن',
    monthlyRent:'کرێی مانگانە', payDayNum:'ڕۆژی پارەدان (1–31)',
    propertyType:'جۆری ملک', residential:'نیشتەجێبوون',
    villa:'ڤیلا', commercial:'بازرگانی', office:'ئۆفیس',
    contractStart:'دەستپێکی گرێبەست', contractEnd:'کۆتایی گرێبەست',
    notes:'تێبینی (ئارەزوومەندانە)', exportCSV:'دەرهێنانی CSV',
    owner:'خاوەن', paid:'پارەدراو', totalTenants:'کۆی گشتی',
    allPaidLabel:'هەموو پارەدراون', phoneTip:'عێراق: 9647701234567 | ئیمارات: 971501234567',
    cancelAdd:'پاشگەزبوونەوە', hideForm:'شاردنەوەی فۆرم', showForm:'زیادکردنی بنکەنشین',
    paymentsTitle:'پارەدانەکان', paymentsSub:'کلیک بکە بۆ گۆڕانی دۆخ: چاوەڕوان پارەدراو',
    addMonth:'+ زیادکردنی مانگ', markPaid:'وەک پارەدراو نیشانەبکە', markPending:'چاوەڕوان',
    printReceipt:'چاپکردنی پسووڵە', noPaymentRecords:'تۆمار نییە. کلیک بکە + زیادکردنی مانگ.',
    paidStatus:'پارەدراو', pendingStatus:'چاوەڕوان', lateStatus:'دواکەوتوو',
    month:'مانگ', paidDate:'بەرواری پارەدان', amount:'بڕ',
    searchTenants:'گەڕان بۆ بنکەنشین...', totalPaid:'کۆی پارەدراو',
    totalPending:'کۆی چاوەڕوان', totalLate:'کۆی دواکەوتوو',
    expensesTitle:'خەرجەکان', expensesSub:'شوێنکەوتنەوەی خەرجی چاکسازی و ملک',
    addExpense:'+ زیادکردنی خەرج', editExpense:'دەستکاریکردنی خەرج', noExpenses:'خەرج نییە هێشتا.',
    description:'وەسف', category:'پۆل', property:'ملک',
    date:'بەروار', total:'کۆی گشتی', totalExpenses:'کۆی خەرجەکان',
    maintenance:'چاکسازی', utilities:'خزمەتگوزاری', repairs:'ڕەمانەوە',
    cleaning:'پاکیزەکردن', management:'بەڕێوەبردن', other:'تر',
    expenseRecords:'تۆمار',
    reportsTitle:'ڕاپۆرتەکان', reportsSub:'پوختەی دارایی',
    totalCollected:'کۆی کۆکراوە', totalExp:'کۆی خەرجەکان',
    revenueByTenant:'داهات بەپێی بنکەنشین', expByCategory:'خەرج بەپێی پۆل',
    downloadCSV:'داگرتنی CSV', print:'چاپکردن',
    noExpensesYet:'خەرجی تۆمارکراو نییە هێشتا.',
    waTitle:'واتساپ', waSub:'بیرخستنەوەی ئۆتۆماتیکی ڕۆژانە کاتژمێر 9',
    connectionStatus:'دۆخی پەیوەندی', sendAll:'ناردن بۆ هەموو',
    sendReminder:'بیرخستنەوە', activityLogs:'تۆماری چالاکی', clearLogs:'سڕینەوە',
    connected:'بەستراوەتەوە', scanQRCode:'کۆدی QR بسکانە', starting:'دەستپێدەکات...',
    waReadyShort:'بەستراوە', waQrShort:'QR',
    disconnected:'بڕابوویەوە', serverOffline:'سێرڤەر ئۆفلاینە',
    scanInstruction:'واتساپ بکەرەوە پێڕست ئامێری بەستراوە بەستنی ئامێر',
    autoReconnecting:'بەستنەوەی ئۆتۆماتیکی...', hasPending:'پارەدانی چاوەڕوانی هەیە', allPaidWA:'هەموو پارەدراون',
    noTenantsWA:'بنکەنشین نییە', sendAllBtn:'ناردن بۆ هەموو',
    settingsTitle:'ڕێکخستنەکان', settingsSub:'ڕێکخستنی سیستەم بۆ کارەکەت',
    businessSettings:'ڕێکخستنی بازرگانی', appName:'ناوی بەرنامە',
    companyName:'ناوی کۆمپانیا', appLogo:'لۆگۆی کۆمپانیا', chooseLogo:'هەڵبژاردنی لۆگۆ', removeLogo:'سڕینەوەی لۆگۆ',
    contractCoordinator:'ڕێکخەری گرێبەست', currency:'دراو', timezone:'کاتی هەرێم',
    reminderHour:'کاتژمێری بیرخستنەوە (0–23)', saveSettings:'پاشەکەوتکردنی ڕێکخستن',
    security:'ئەمنیت', currentPassword:'وشەی نهێنی ئێستا',
    newUsername:'ناوی بەکارهێنەری نوێ (ئارەزوومەندانە)', newPassword:'وشەی نهێنی نوێ (ئارەزوومەندانە)',
    updateCredentials:'نوێکردنەوەی زانیاری داخل بوون', keepCurrent:'بەتاڵ بهێڵە بۆ مانەوەی ئێستایی',
    messageTemplates:'قاڵبی پەیامی واتساپ',
    reminderMsg:'پەیامی بیرخستنەوە', lateMsg:'ئاگادارکردنەوەی پارەدانی دواکەوتوو',
    saveTemplates:'پاشەکەوتکردنی قاڵبەکان', availableVars:'گۆڕاوە بەردەستەکان',
    usersTitle:'بەکارهێنەران', usersSub:'بەڕێوەبردنی ئەندامان',
    addUser:'+ زیادکردنی بەکارهێنەر', editUser:'دەستکاریکردنی بەکارهێنەر', noUsers:'بەکارهێنەر نییە هێشتا.',
    createdBy:'دروستکراوە لەلایەن', createdAgents:'ئەندامە دروستکراوەکان', passwordHidden:'شاراوە - تەنها نوێکردنەوە',
    role:'ڕۆڵ', agent:'ئەندام', adminRole:'بەڕێوەبەر', ownerRole:'خاوەن / بەڕێوەبەر', developerRole:'گەشەپێدەر', email:'ئیمەیڵ',
    createUser:'دروستکردنی بەکارهێنەر', deleteUser:'سڕینەوەی بەکارهێنەر',
    agentReports:'ڕاپۆرتی ئەندامان', agentReportsSub:'پێداچوونەوەی چالاکی خاوەن و ئەندامان',
    totalActivity:'کۆی چالاکی', lastActivity:'دوایین چالاکی',
    youLabel:'تۆ', nameLabel:'ناوی تەواو',
    receiptTitle:'پسووڵەی پارەدان', receiptNo:'ژمارەی پسووڵە',
    receiptDate:'بەروار', receiptTenant:'بنکەنشین', receiptProperty:'ملک',
    receiptPeriod:'ماوە', receiptAmount:'بڕی پارەدراو', receiptStatus:'دۆخ',
    receiptNote:'ئەمە پسووڵەی پارەدانی فەرمییە.',
    darkMode:'دۆخی تاریک', lightMode:'دۆخی ڕووناک',
    language:'زمان',
    renewalMsg:'پەیامی نوێکردنەوەی گرێبەستی کرێ',
    renewRentContract:'نوێکردنەوەی گرێبەستی کرێ',
    renewRentContractsTitle:'نوێکردنەوەی گرێبەستەکانی کرێ',
    renewRentContractsSub:'شوێنکەوتنی گرێبەستەکانی کرێ کە نزیکن لە نوێکردنەوە و ناردنی بیرخستنەوەی واتساپ.',
    sendRenewalReminder:'ناردنی بیرخستنەوەی نوێکردنەوە',
    sendAllRenewals:'ناردن بۆ هەموویان',
    renewalDueSoon:'نزیکی نوێکردنەوە',
    expired:'بەسەرچوو',
    daysLeft:'ڕۆژی ماوە',
    noRenewals:'هیچ گرێبەستی کرێ نزیک لە نوێکردنەوە نییە.',
    renewalWindow:'ماوەی بیرخستنەوە',
    notifications:'ئاگادارکردنەوەکان',
    notificationsSub:'ئاگاداری بۆ تیم بنێرە و ئەوە ببینە کێ خوێندوویەتی.',
    sendNotification:'ناردنی ئاگادارکردنەوە',
    notificationTitle:'سەردێڕ',
    notificationMessage:'پەیام',
    scheduledAt:'کاتی ناردن',
    sendByWhatsapp:'ناردن بە واتساپ',
    sendToAllAgents:'ناردن بۆ هەموو ئەندامان',
    selectAgents:'هەڵبژاردنی ئەندامان',
    unread:'نەخوێندراو',
    read:'خوێندراو',
    markAsRead:'وەک خوێندراو',
    noNotifications:'هیچ ئاگادارکردنەوەیەک نییە.',
    sentNotifications:'ئاگادارکردنەوە نێردراوەکان',
    profit:'قازانج',
    profitTitle:'قازانج',
    profitSub:'قازانجی گرێبەست، خەرجی و قازانجی پاک ببینە.',
    recordProfit:'تۆمارکردنی قازانج',
    profitAmount:'بڕی قازانج',
    profitCurrency:'دراوی قازانج',
    saveProfitAndPrint:'پاشەکەوتی قازانج و چاپ',
    printWithoutProfit:'چاپ بەبێ قازانج',
    profitPromptTitle:'قازانجی گرێبەست',
    profitPromptSub:'پێش چاپکردن، بڕی قازانجی وەرگیراو تۆمار بکە.',
    fromDate:'لە',
    toDate:'بۆ',
    exportExcel:'دەرکردنی Excel',
    grossProfit:'کۆی قازانج',
    netProfit:'قازانجی پاک',
    noProfits:'هیچ قازانجێک تۆمار نەکراوە.',
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => localStorage.getItem('rp_lang') || 'en');

  function setLang(l) {
    setLangState(l);
    localStorage.setItem('rp_lang', l);
    // Apply RTL direction + lang attribute to <html>
    document.documentElement.lang = l;
    document.documentElement.dir  = (l === 'ar' || l === 'ku') ? 'rtl' : 'ltr';
  }

  // Apply on mount
  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir  = (lang === 'ar' || lang === 'ku') ? 'rtl' : 'ltr';
  }, []);

  const t = (key) => T[lang]?.[key] ?? T.en[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
